name: bienaventurados
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  flutter_local_notifications: ^9.0.0
  flutter_native_timezone: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  screenshot: ^1.2.3
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+4
  timezone: ^0.8.0

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter_icons:
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true
  ios: true
  adaptive_icon_background: "#9147fe"
  adaptive_icon_foreground: "assets/images/ic_foreground_variant.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Book.ttf
        - asset: assets/fonts/Gotham-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Bold.ttf
          weight: 900
