name: bienaventurados
description: Aplicación católica de Ser Eucaristía.
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.3
  firebase_in_app_messaging: ^0.5.0+10
  firebase_messaging: ^10.0.8
  flutter:
    sdk: flutter
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  flutter_local_notifications: ^9.0.0
  flutter_native_timezone: ^2.0.0
  google_sign_in: ^5.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  screenshot: ^1.2.3
  share: ^2.0.4
  shared_preferences: ^2.0.6
  social_share:
    git:
      url: https://github.com/mikaelim-id/social_share
  sqflite: ^2.0.0+4
  styled_widget: ^0.4.0+3
  timezone: ^0.8.0

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter_native_splash:
  android: true
  # ios: true
  # web: true
  color: "#F9FAFE"
  image: "assets/splash.png"

  android_gravity: center
  # ios_content_mode: center
  # web_image_mode: center
  color_dark: "#232733"
  image_dark: "assets/images/splash-dark.png"
  fullscreen: true

flutter_icons:
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true
  ios: true
  adaptive_icon_background: "#F9FAFE"
  adaptive_icon_foreground: "assets/images/ic_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Book.ttf
        - asset: assets/fonts/Gotham-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Bold.ttf
          weight: 900
